# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Pett
email: dejp3@cam.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  A personal site for my work in museums, heritage, technology and beyond.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://museologi.st"
twitter_username: dejpett
github_username:  portableant
paginate: 12
paginate_path: "/blog/page/:num/"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
permalink: pretty
read_time: true
words_per_minute: 200
google_analytics: UA-298202-5
collections:
   blog:
      output: true
      permalink: /:collection/:name
   projects:
      output: true
      permalink: /:collection/:slug
   technologies:
      output: true
      permalink: /:collection/:name
